import {test} from 'node:test';
import assert from 'node:assert/strict';
import {formatLivePosReport,registerOwnerHandlers} from '../src/owner.js';
function fixture({owner=true,online=true}={}){const actions=[],commands={},calls=[],messages=[];
 const bot={command:(name,fn)=>commands[name]=fn,action:(pattern,fn)=>actions.push({pattern,fn})};
 const fetchImpl=async(url,options)=>{const body=JSON.parse(options.body);calls.push({url,options,body});if(url.endsWith('/access')&&!owner)return{ok:false,status:403,json:async()=>({error:'Доступ запрещён',code:'OWNER_FORBIDDEN'})};if(url.endsWith('/live-report')&&!online)return{ok:false,status:409,json:async()=>({error:'POS не активен',code:'POS_OFFLINE'})};if(url.endsWith('/live-report'))return{ok:true,status:200,json:async()=>({report:{shiftOpen:true,generatedAt:1,employeeName:'Анна',currency:'BYN',orders:2,revenue:30,cash:10,card:20,categories:[{name:'Пицца',quantity:2,revenue:30}],products:[{name:'Маргарита',quantity:2,revenue:30}]}})};return{ok:true,status:200,json:async()=>({kind:'bind',venue:'Кафе',employeeName:'Owner'})};};
 const start=registerOwnerHandlers(bot,{backendUrl:'https://example.test',secret:'s'.repeat(43),fetchImpl});
 const ctx={chat:{type:'private'},from:{id:123,first_name:'Owner'},startPayload:'owner_'+'t'.repeat(43),reply:async(...args)=>messages.push(args),answerCbQuery:async()=>{},editMessageText:async m=>messages.push([m])};
 return{actions,commands,calls,messages,start,ctx};
}
test('ordinary checkout /start passes through; Owner uses existing bot',async()=>{const f=fixture();f.ctx.startPayload='checkout-token';assert.equal(await f.start(f.ctx),false);assert.equal(f.calls.length,0);});
test('owner link confirms actual sender and uses authenticated backend callback',async()=>{const f=fixture();assert.equal(await f.start(f.ctx),true);assert.equal(f.calls[0].body.telegramId,'123');assert.equal(f.calls[0].options.headers['X-Owner-Bot-Secret'],'s'.repeat(43));const keyboard=f.messages[0][1].reply_markup.inline_keyboard;assert.ok(keyboard[0][0].callback_data.length<=64);assert.match(f.messages[0][0],/PIN в Telegram вводить не нужно/);});
test('group chat and bot sender cannot bind or recover',async()=>{for(const mode of ['group','bot']){const f=fixture();if(mode==='group')f.ctx.chat.type='supergroup';else f.ctx.from.is_bot=true;await f.start(f.ctx);assert.equal(f.calls.length,0);assert.match(f.messages[0][0],/личном чате/);}});
test('approval callback takes user ID from Telegram context, never callback payload',async()=>{const f=fixture();const handler=f.actions.find(x=>x.pattern instanceof RegExp&&x.pattern.test('oa_'+'t'.repeat(43)));f.ctx.match=handler.pattern.exec('oa_'+'t'.repeat(43));f.ctx.from.id=456;await handler.fn(f.ctx);assert.equal(f.calls[0].body.telegramId,'456');assert.equal(f.calls[0].body.action,'approve');});
test('myid is available only in private chat and does not send credentials',async()=>{const f=fixture();f.ctx.chat.type='group';await f.commands.myid(f.ctx);assert.equal(f.messages.length,0);f.ctx.chat.type='private';await f.commands.myid(f.ctx);assert.equal(f.messages[0][0],'Ваш Telegram ID: 123');assert.equal(f.calls.length,0);});
test('configured owner receives the information button while other users keep normal flow',async()=>{const owner=fixture();owner.ctx.startPayload='';assert.equal(await owner.start.showMenu(owner.ctx),true);assert.equal(owner.calls[0].body.telegramId,'123');assert.equal(owner.messages[0][1].reply_markup.inline_keyboard[0][0].callback_data,'owner_live_report');const guest=fixture({owner:false});guest.ctx.startPayload='';assert.equal(await guest.start.showMenu(guest.ctx),false);assert.equal(guest.messages.length,0);});
test('information button returns current shift categories, products and payment totals',async()=>{const f=fixture();const action=f.actions.find(x=>x.pattern==='owner_live_report');await action.fn(f.ctx);assert.match(f.messages[0][0],/Выручка:/);assert.match(f.messages[0][0],/Наличные:/);assert.match(f.messages[0][0],/Карта:/);assert.match(f.messages[0][0],/Пицца/);assert.match(f.messages[0][0],/Маргарита/);});
test('offline POS produces a clear owner response',async()=>{const f=fixture({online:false});const action=f.actions.find(x=>x.pattern==='owner_live_report');await action.fn(f.ctx);assert.match(f.messages[0][0],/POS не активен/);});
test('closed shift still proves POS is online',()=>{assert.equal(formatLivePosReport({shiftOpen:false}),'🟢 POS онлайн\n\nОткрытой смены сейчас нет.');});
